### PR TITLE
Add instructions for testing this repo

### PR DESCRIPTION
**Pull request by klonos**

### CODE REVIEW

**Comment by ghost** [comment]
I feel like this would be better as a README in the `.tugboat` directory... That directory is the only difference between this repo and Backdrop's repo, so I like the fact that Backdrop stays 'pure' (for lack of a better word) and this repos changes are contained to a separate directory (it also makes it easier for merging in new versions of Backdrop).

**Comment by quicksketch** [comment]
Agreed with @BWPanda. Although it'd be nice to have better text displayed on the GitHub project page, we regularly merge directly from the main Backdrop repo. Anything that touches a core file (including the README.md) will result in eventual conflicts when pulling. If we switch to a different approach (e.g. pulling down the latest release via a release archive instead) then we could not worry about the Git history.

**Comment by ghost** [comment]
Hmm, interesting idea... I could change this repo to just be the .tugboat dir and a readme, then add code to tugboat to download the latest stable release of Backdrop each time. That'd save updating this repo manually too. Leave it with me 😊

**Comment by ghost** [comment]
Fixed in new repo: https://github.com/backdrop-ops/tugboat-demos Feel free to open an issue/PR there if this needs more work.

**Pull request closed without merging**
